on:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x.x

      - name: Install dependencies
        run: |
          dotnet --version
          dotnet tool install workflow
          dotnet workflow restore
          dotnet restore
          dotnet build
