on:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x.x
          cache: true

      - name: Install dependencies
        run: |
          dotnet workload restore
          dotnet restore
          dotnet test || true
          dotnet build --configuration Release

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wasm-artifact
          path: Music21NET.WASM/bin/Release/net8.0/browser-wasm/
