on:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x.x

      - name: Install dependencies
        run: |
          dotnet workload restore
          dotnet restore
          dotnet test || true
          dotnet build -c Release

      - name: upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: wasm-artifact
          path: Music21NET.WASM/bin/Release/net8.0
